#!/bin/bash
git clone https://github.com/courtois-neuromod/anat-processing-book.git content/analysis
ls .
ls ..
ls ../../
ls ../data
ls ../data/courtois-anat-neurolibre/
find / -name "courtois-anat-neurolibre"
cp -r ../data/courtois-anat-neurolibre/courtois-anat-neurolibre content/analysis/source/data
